apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cobol-api
    run: cobol-api
  name: cobol-api
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cobol-api
      run: cobol-api
  template:
    metadata:
      labels:
        app: cobol-api
        run: cobol-api
    spec:
      containers:
        - image: claudio2424/cobol-cloud:latest
          imagePullPolicy: Always
          name: cobol-api
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"
            limits:
              memory: "650Mi"
              cpu: "500m"
            
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cobol-api
  name: cobol-api
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8000
    nodePort: 31181
    protocol: TCP
    targetPort: 8000
  selector:
    run: cobol-api
  type: NodePort